### PR TITLE
Add nix flake + direnv config, improve readme

### PR DESCRIPTION
**Pull request by elizagamedev**
The introduction of a nix flake makes it easier to build and flash the firmware with the Nix package manager.

Besides being tweaked to describe Nix usage instructions, more information has been added to the readme to make building the monocle more accessible to people who do not use VSCode.

### CODE REVIEW

**Review by josuah — COMMENTED** [review]
Thank you for this!
Always good to get build system work in more contexts.
I passed a message around for review by the core team.

**Comment by josuah** [comment]
For everyone's review convenience:
https://direnv.net/
https://nixos.wiki/wiki/Flakes

**Comment by siliconwitch** [comment]
Super cool! It would be quite nice to clean the readme up a little more and follow a straightforward build system like this. Unfortunately, it seems the [gcc-arm-embedded](https://search.nixos.org/packages?channel=22.11&show=gcc-arm-embedded&from=0&size=50&sort=relevance&type=packages&query=gcc+arm+embedded) package on nix is an older one which didn't support ARM Macs. The nRF command line tools are also shown as Linux only (here it seems the maintainer just didn't bother to add the Mac option to the .nix file). I guess these are easily fixable, but until then it might cause Mac folks some headaches if they try to follow these instructions

**Comment by elizagamedev** [comment]
That's unfortunate. I'll add a bit about how those packages don't yet work on macos when I get a chance.

**Comment by siliconwitch** [comment]
Let me know if you still want to finish this. Closing in the meantime

**Pull request closed without merging**
